config/routes.rb
NestedExample::Application.routes.draw do

  resources :parents do
    resources :children
  end

end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :parent
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :children
  accepts_nested_attributes_for :children
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

  def index
    @parent= Parent.find(params[:parent_id])
    @children = @parent.children.all
  end


  def show
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
  end

  def new
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.new
  end

  def edit
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
  end

  def create
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.new(child_params)

      if @child.save
        redirect_to [@parent, @child], notice: 'Child was successfully created.'
      else
        render action: 'new'
      end
  end


  def update
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
      if @child.update(child_params)
        redirect_to [@parent, @child], notice: 'Child was successfully updated.'
      else
       render action: 'edit'
      end
  end


  def destroy
    @parent = Parent.find(params[:parent_id])
    @child = @parent.children.find(params[:id])
    @child.destroy
    redirect_to parent_children_path(@parent)
  end

  private
    def child_params
      params.require(:child).permit(:name)
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController

  def index
    @parents = Parent.all
  end

  def show
    @parent = Parent.find(params[:id])
  end

  def new
    @parent = Parent.new
  end

  def edit
    @parent = Parent.find(params[:id])
  end


  def create
    @parent = Parent.create(params[:parent].permit(:name, :children_attributes=>[:name]))
    if @parent.save
      redirect_to @parent, notice: 'Parent was successfully created.'
    else
      render action: 'new'
    end
  end


  def update
    @parent = Parent.find(params[:id])
    if @parent.update(parent_params)
      redirect_to @parent, notice: 'Parent was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @parent = Parent.find(params[:id])
    @parent.destroy
    redirect_to parents_url
  end

  private
    def parent_params
      params.require(:parent).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/children/_form.html.erb
<%= form_for([@parent, @child]) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', parent_child_path(@parent, @child) %> |
<%= link_to 'Back', parent_children_path(@parent) %>

app/views/children/index.html.erb
<h1><%=@parent.name%>'s Children</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent ID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.parent_id %></td>
        <td><%= link_to 'Show', parent_child_path(@parent, child) %></td>
        <td><%= link_to 'Edit', edit_parent_child_path(@parent, child) %></td>
        <td><%= link_to 'Destroy', [@parent, child], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_parent_child_path(@parent) %>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', parent_children_path(@parent) %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @child.name %>
</p>

<p>
  <strong>Parent ID:</strong>
  <%= @child.parent_id %>
</p>

<%= link_to 'Edit', edit_parent_child_path(@parent, @child) %> |
<%= link_to 'Back', parent_children_path(@parent) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <% @parent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<h1>Listing parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Show Kids', parent_children_path(parent) %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New parent</h1>

<%= form_for @parent do |f| %>
  <%= f.text_field :name, placeholder: "Name of Parent" %>
  <%= f.fields_for :children, @parent.children.build do |b| %>
    <%= b.text_field :name, placeholder: "Child's Name" %>
  <% end %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>